apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /   # ALB health check
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
