apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-namespace
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
